### ISSUE TITLE
Unit Test Examples

### ISSUE THREAD

**Issue by zip-hashan** [sizovs/PipelinR#22]
Hi There, 

Could you please include how to unit test the functionality in Kotlin/Java and Spring boot?

Cheers 🙂

**Comment by sizovs** [comment]
Hi @zip-hashan 

Is there a specific testing challenge you're trying to overcome? All command/notification handlers are POJOs, so you can easily test them with your favorite unit testing and mocking library.

**Comment by zip-hashan** [comment]
Hi @sizovs, I am using MockK with JUnit and AssertJ on a Spring boot application. So, wondering how to mock Pipelinr handlers when using @MockK and @InjectMockKs annotations? 🤔

**Comment by sizovs** [comment]
@zip-hashan Just create an instance of Handler and provide mocks via constructor:

```kotlin
@Test
fun showsHowToTestHandlersWithMockk() {
  val dep1 = mockk<Dependency1>()
  val dep2 = mockk<Dependency2>()
  val handler = YourCommandHandler(dep1, dep2)
  var command = YourCommand()
  val result = handler.handle(command)
  assertNotNull(result)
}


```
