### ISSUE TITLE
How to make it work with Quarkus cdi?

### ISSUE THREAD

**Issue by dambros** [sizovs/PipelinR#23]
Would you mind helping me setting up the dependency injection for Quarkus since with Quarkus alone I won't have access to Spring's ObjectProvider.

**Comment by sizovs** [comment]
Hi @dambros 

With CDI, you have to use BeanFactory instead of ObjectProvider:

```
Set<Command.Handler> handlers = beanFactory.getBeans(Command.Handler.class);
Pipeline pipeline = new Pipelinr().with(() -> handlers.stream()).
```

Did that help?

**Comment by sizovs** [comment]
Hi @dambros 

It's out of PipelinR's scope, as PipelinR is DI library/framework agnostic. The better place to learn how to use Quarkus DI is Quarkus docs or community.
