### ISSUE TITLE
Can't override method matches in Notification.Handler

### ISSUE THREAD

**Issue by vitalii-honchar** [sizovs/PipelinR#24]
**Problem**
Can't override matches method in implementation of `Notification.Handler`.

**Steps to Reproduce**
Just launch this test:
```Java
import org.junit.jupiter.api.Test;

public class PipelinrMatchesTest {

    class Event1 implements Notification {}

    class Event2 implements Notification {}

    class TestHandler1 implements Notification.Handler<Event1> {

        @Override
        public void handle(Event1 notification) {

        }

        @Override
        public boolean matches(Event1 notification) {
            return Notification.Handler.super.matches(notification);
        }
    }

    class TestHandler2 implements Notification.Handler<Event2> {
        @Override
        public void handle(Event2 notification) {

        }
    }

    @Test
    void testMatches() {
        Notification.Handler handler1 = new TestHandler1();
        Notification.Handler handler2 = new TestHandler2();

        Event1 event1 = new Event1();
        Event2 event2 = new Event2();

        System.out.println(handler1.matches(event1));
        System.out.println(handler2.matches(event2));

        System.out.println(handler1.matches(event2));
        System.out.println(handler2.matches(event1));
    }
}
```

Exception will throws on line `System.out.println(handler1.matches(event2));`.

Class `an.awesome.pipelinr.Pipelinr` uses handlers without generic specification, so this will be reproduced in Pipelinr usage with override method matches.

**Expected Result**
Success complete test execution.

**Actual Result**
```
class an.awesome.pipelinr.PipelinrMatchesTest$Event2 cannot be cast to class an.awesome.pipelinr.PipelinrMatchesTest$Event1 (an.awesome.pipelinr.PipelinrMatchesTest$Event2 and an.awesome.pipelinr.PipelinrMatchesTest$Event1 are in unnamed module of loader 'app')
java.lang.ClassCastException: class an.awesome.pipelinr.PipelinrMatchesTest$Event2 cannot be cast to class an.awesome.pipelinr.PipelinrMatchesTest$Event1 (an.awesome.pipelinr.PipelinrMatchesTest$Event2 and an.awesome.pipelinr.PipelinrMatchesTest$Event1 are in unnamed module of loader 'app')
	at an.awesome.pipelinr.PipelinrMatchesTest$TestHandler1.matches(PipelinrMatchesTest.java:13)
	at an.awesome.pipelinr.PipelinrMatchesTest.testMatches(PipelinrMatchesTest.java:49)
```

**Comment by sizovs** [comment]
Hey

A quick look at the code tells me that's it's expected behavior, as handlers can only handle events that match its generic signature:

👌 System.out.println(handler1.matches(event1));
 
❌  System.out.println(handler1.matches(event2));

Did I miss something?

**Comment by sizovs** [comment]
Got it. Do you have time/energy/capacity for a PR?

**Comment by sizovs** [comment]
Hi @vitalii-honchar 

I've added a test demonstrating custom notification handling: https://github.com/sizovs/PipelinR/commit/6d1f9e82a8015e47accc4de58ef36d7420c83d23.

Custom notification handlers work as long as you don't call `super.matches() from a custom notification handler (which, I suppose, you can avoid calling in your usecase). To have a "catch-all" notification handler, don't override matches.
