### ISSUE TITLE
Javadoc jars?

### ISSUE THREAD

**Issue by dstutz** [sizovs/PipelinR#29]
Would it be possible to create javadoc jars that have content?  I see they exist in maven central (eg https://repo1.maven.org/maven2/net/sizovs/pipelinr/0.8/pipelinr-0.8-javadoc.jar)  but are essentially empty save for a META-INF/MANIFEST.MF.  I took a quick look but am completely unfamiliar with gradle.

**Comment by sizovs** [comment]
@dstutz I'll make sure JavaDocs are included in the next releases. Good news is that not many JavaDocs you need to read to use PipelinR ; )

**Comment by dstutz** [comment]
I 100% agree and this is totally me picking nits.  It really is a powerful framework for how few classes the user actually needs to use.  Was just looking through the NotificationHandlingStrategy implementations by reading the sources and just figured it would be slightly less friction to be able to look where the JavaDocs spoon feed you with "All Known Implementing Classes:" like here: https://jakarta.ee/specifications/platform/8/apidocs/javax/faces/convert/converter
And now that I have read all of them I don't really need it anymore but figure it can only help someone else.

**Comment by sizovs** [comment]
@dstutz Javadocs have been included in 0.9. 🙏
