### ISSUE TITLE
Question: Error management

### ISSUE THREAD

**Issue by sashokbg** [sizovs/PipelinR#33]
Hello, are there any mechanisms implemented in this library for error management ? 

For example most asynchronous frameworks like js Promise has _resolve_ / _reject_, rxjs has _catch_, _retry_ and _retryWhen_ or Project Reactor's _onErrorResume_ and so on.

**Comment by sizovs** [comment]
Hi @sashokbg 

According to the [Async section in README](https://github.com/sizovs/PipelinR#async), Commands can return anything, including CompletableFuture (Java), Mono/Flux (Spring), or Observable (RxJava). All these types support asynchronous error handling. How they do this can be looked up in their JavaDocs.

**Comment by sashokbg** [comment]
Thank you for your answer, I haven't thought about this scenario.
So to put it simple we can wrap the return value either in some Async class or even use Optional ?

**Comment by sizovs** [comment]
Yes, that should work (and cover most of the use cases). If this solution doesn't fit your use case nicely, and you think that PipelinR needs more advanced/internal async support, please re-open this issue, and we'll figure something out.
