### ISSUE TITLE
GroupId for maven in README cannot be resolved

### ISSUE THREAD

**Issue by jianghongfei** [sizovs/PipelinR#6]
GroupId for maven in README is `an.awesome.pipelinr`, but it cannot be resolved. While `an.awesome` for gradle works fine. So I suppose `an.awesome` is the right one. 

BTW, maven complains if no version was specified in dependency :
```
'dependencies.dependency.version' for an.awesome:pipelinr:jar is missing.
```

**Comment by sizovs** [comment]
@jianghongfei thanks, fixed in https://github.com/sizovs/PipelinR/commit/ea0e1a027cd8373f5f4f5277411735b91863daeb
