### ISSUE TITLE
Throwing Exceptions

### ISSUE THREAD

**Issue by pratiksinghal48** [sizovs/PipelinR#7]
Hello

Recently I got a chance to work on a project using .NET Core and got to know about mediatR. Right from then, I was searching something similar for Java and found PipelinR.

I want to know how to throw exceptions from the handler. I mean there is no need to add throws in c# as required in Java, so Mediatr have no problem. But how I can achieve same in PipelinR.

**Comment by sizovs** [comment]
Hi @pratiksinghal48 

In Java, you don't need to add throws, if you use unchecked exceptions (ones that derive from `RuntimeException`). So if you want to throw a runtime exception from PipelinR – just do if. If you use an API, that throws a checked exception (a one that derives from `Exception`), then wrap it with the unchecked exception and you are all set.
