### ISSUE TITLE
Feature request: Notification support?

### ISSUE THREAD

**Issue by rdehuyss** [sizovs/PipelinR#9]
Hi doing both .Net and Java, I was really happy to find pipelinr which seems like a great Java alternative for mediatr.

I do have a question: will you support notifications or is there a reason it is not there yet? In our application I see several use cases for notifications.

**Comment by sizovs** [comment]
Hi @rdehuyss 

To keep the library functionally slim, there is no plan to support notifications. In cases when notifications are useful, they can be implemented with a single Command that invokes multiple services (aka notifications). 

If the aforementioned solution doesn't fit your use case, please describe it here, we'll find out the best solution. 👍

– Eduards

**Comment by sizovs** [comment]
@rdehuyss 

Notification support has been added in v0.5.
